---
- name: create docker config directory
  file:
    path: /etc/docker
    state: directory
    mode: 0755
  when: docker_daemon_reconfigure | bool

- name: configure docker daemon.json
  vars:
    docker_daemon_options:
      "insecure-registries":
        - "{{ docker_registry }}"
  copy:
    content: "{{ docker_daemon_options | to_nice_json }}"
    dest: "/etc/docker/daemon.json"
  when: docker_daemon_reconfigure | bool

- name: create systemd drop-in directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755
  when:
    - docker_daemon_reconfigure | bool
    - not in_docker

- name: ensure MountFlags=shared
  template:
    src: docker_shared_mountflags.j2
    dest: /etc/systemd/system/docker.service.d/shared.conf
  notify:
    - restart docker
  when:
    - docker_daemon_reconfigure | bool
    - not in_docker

- name: Get stat of libvirtd apparmor profile
  stat: path=/etc/apparmor.d/usr.sbin.libvirtd
  register: apparmor_libvirtd_profile
  when: ansible_distribution == "Ubuntu"

- name: Remove apparmor profile for libvirt
  command: apparmor_parser -R /etc/apparmor.d/usr.sbin.libvirtd
  become: True
  ignore_errors: True
  when:
    - ansible_distribution == "Ubuntu"
    - apparmor_libvirtd_profile.stat.exists

- name: Create docker group
  group:
    name: docker
  become: True

- name: Add kolla user to docker group
  user:
    name: kolla
    append: yes
    groups: docker
  become: True
  when: create_kolla_user | bool

- name: Stop time service
  service:
    name: ntp
    state: stopped
  become: True
  when:
    - ansible_os_family == "Debian"
    - enable_host_ntp | bool

- name: Stop time service
  service:
    name: ntpd
    state: stopped
  become: True
  when:
    - ansible_os_family == "RedHat"
    - enable_host_ntp | bool

- name: Synchronizing time one-time
  command:  ntpd -gq
  become: True
  when: enable_host_ntp | bool

- name: Start time sync service
  service:
    name: ntp
    state: started
    enabled: yes
  become: True
  when:
    - ansible_os_family == "Debian"
    - enable_host_ntp | bool

- name: Start time sync service
  service:
    name: ntpd
    state: started
    enabled: yes
  become: True
  when:
    - ansible_os_family == "RedHat"
    - enable_host_ntp | bool

- name: Disable selinux
  selinux:
    policy: target
    state: permissive
  become: true
  when:
    - disable_selinux | bool
    - ansible_os_family == "RedHat"

- name: Reboot
  command: reboot -f
  become: True
  when:
    - reboot_required is defined
    - reboot_required | bool
