---
collectd_services:
  collectd:
    container_name: collectd
    group: collectd
    enabled: true
    image: "{{ collectd_image_full }}"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/collectd/:{{ container_config_directory }}/:ro"
      - "{{node_config_directory }}/collectd/collectd.conf.d/:/etc/collectd/collectd.conf.d/"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/log/kolla_logs:/var/log/kolla/"
      - "/sys/:/sys/:ro"
      - "/dev/:/dev/:ro"

####################
# Docker
####################
collectd_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-collectd"
collectd_tag: "{{ openstack_release }}"
collectd_image_full: "{{ collectd_image }}:{{ collectd_tag }}"

####################
# OpenStack
####################
collectd_logging_debug: "{{ openstack_logging_debug }}"

# Ceph metrics
collectd_ceph_rados_bench_enabled: no
collectd_ceph_rados_bench_interval: 60
collectd_ceph_mon_stats_enabled: yes
collectd_ceph_mon_stats_interval: 10
collectd_ceph_osd_stats_enabled: yes
collectd_ceph_osd_stats_interval: 10
collectd_ceph_pg_enabled: yes
collectd_ceph_pg_interval: 10
collectd_ceph_pool_enabled: yes
collectd_ceph_pool_interval: 10
