---
- include: ../../ceph_pools.yml
  vars:
    pool_name: rbd
    pool_type: replicated
    disk_type: ssd

- name: Ensuring config directory exists
  file:
    path: "{{ item }}"
    state: "directory"
  when: inventory_hostname in groups['ceph']
  with_items:
    - /etc/ceph
    - /tmp/secrets

- name: Copying over ceph.conf(s)
  merge_configs:
    sources:
      - "{{ role_path }}/../ceph/templates/ceph.conf.j2"
      - "{{ node_custom_config }}/ceph.conf"
      - "{{ node_custom_config }}/ceph/{{ inventory_hostname }}/ceph.conf"
    dest: "/etc/ceph/ceph.conf"
  when: inventory_hostname in groups['ceph']

- name: Pulling cephx keyring for rbd
  command: docker exec ceph_mon ceph auth get-or-create client.rbd mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=rbd'
  register: cephx_key
  delegate_to: "{{ groups['ceph-mon'][0] }}"
  changed_when: False
  run_once: True

- name: Pulling rbd cephx keyring for libvirt
  command: docker exec ceph_mon ceph auth get-key client.rbd
  register: rbd_cephx_raw_key
  delegate_to: "{{ groups['ceph-mon'][0] }}"
  changed_when: False
  run_once: True

- name: Pushing cephx keyring for rbd
  copy:
    content: "{{ cephx_key.stdout }}\n\r"
    dest: "/etc/ceph/ceph.client.rbd.keyring"
    mode: "0600"
  when: inventory_hostname in groups['ceph']

- name: Pushing secrets xml for libvirt
  vars:
    uuid: "{{ rbd_secret_uuid }}"
    name: client.rbd secret
  template:
    src: "secret.xml.j2"
    dest: "/tmp/secrets/{{ uuid }}.xml"
    mode: "0600"
  when:
    - inventory_hostname in groups['ceph']

- name: Define libvirt secret
  vars:
    uuid: "{{ rbd_secret_uuid }}"
  command: "virsh secret-define /tmp/secrets/{{ uuid }}.xml"

- name: Set rbd secret value
  vars:
    uuid: "{{ rbd_secret_uuid }}"
    content: "{{ rbd_cephx_raw_key.stdout }}"
  command: virsh secret-set-value {{ uuid }} {{ content }}
