---
- include: ceph.yml
  when:
    - enable_ceph | bool and nova_backend == "rbd"
    - inventory_hostname in groups['ceph-mon'] or
        inventory_hostname in groups['compute'] or
        inventory_hostname in groups['nova-api'] or
        inventory_hostname in groups['nova-conductor'] or
        inventory_hostname in groups['nova-consoleauth'] or
        inventory_hostname in groups['nova-novncproxy'] or
        inventory_hostname in groups['nova-scheduler']

- include: external_ceph.yml
  when:
    - not enable_ceph | bool and nova_backend == "rbd"
    - inventory_hostname in groups['compute']

- file:
    path: /var/ait/scripts
    state: directory

- name: Install shutdown-node script
  template:
    src: shutdown-node.sh.j2
    dest: "/usr/sbin/shutdown-node"
    mode: 0755
  when: inventory_hostname in groups['compute']

- name: Install ait_mounts script
  template:
    src: ait_mounts.sh
    dest: "/var/ait/scripts/nova_mounts"
    mode: 0755
  when: inventory_hostname in groups['compute']

- include: register.yml
  when: inventory_hostname in groups['nova-api']

- include: gluster.yml
  when:
    - enable_nova_gluster | bool
    - ait_nova_compute_type == 'p'

- include: lvm.yml
  when: ait_nova_compute_type == 'w'

- include: config.yml

- include: config-nova-fake.yml
  when:
    - enable_nova_fake | bool
    - inventory_hostname in groups['compute']

- include: bootstrap.yml
  when: inventory_hostname in groups['nova-api'] or
        inventory_hostname in groups['compute']

- name: Flush handlers
  meta: flush_handlers

- include: simple_cell_setup.yml
