---
- name: Ensuring collectd config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    recurse: yes
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ collectd_services }}"

- name: Copying over ceph.conf(s)
  merge_configs:
    sources:
      - "{{ role_path }}/../ceph/templates/ceph.conf.j2"
      - "{{ node_custom_config }}/ceph.conf"
      - "{{ node_custom_config }}/ceph/{{ inventory_hostname }}/ceph.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/ceph.conf"
  when:
    - inventory_hostname in groups['collectd']
    - enable_ceph_metrics | bool
  with_dict: "{{ collectd_services }}"

- name: Ensuring Plugin directory exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}/collectd.conf.d"
    state: "directory"
    recurse: yes
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ collectd_services }}"

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
  register: collectd_config_jsons
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ collectd_services }}"
  notify:
    - Restart collectd container

- name: Pulling cephx keyring for collectd
  command: docker exec ceph_mon ceph auth get-or-create client.collectd mon 'allow rx' osd 'allow rx' mgr 'allow rx'
  register: cephx_key_metric
  delegate_to: "{{ groups['ceph-mon'][0] }}"
  changed_when: False
  run_once: True
  when:
    - enable_ceph_metrics | bool

- name: Pushing cephx keyring
  copy:
    content: "{{ cephx_key_metric.stdout }}\n\r"
    dest: "{{ node_config_directory }}/{{ item.key }}/ceph.client.collectd.keyring"
    mode: "0600"
  with_dict: "{{ collectd_services }}"
  when:
    - enable_ceph_metrics | bool
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool

- name: Copying over collectd.conf for services
  vars:
    service: "{{ collectd_services['collectd'] }}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/collectd/collectd.conf"
  with_first_found:
    - "{{ node_custom_config }}/collectd/{{ inventory_hostname }}/collectd.conf"
    - "{{ node_custom_config }}/collectd/collectd.conf"
    - "{{ node_custom_config }}/collectd.conf"
    - "collectd.conf.j2"
  register: collectd_conf
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart collectd container

- name: Check collectd containers
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    privileged: "{{ item.value.privileged | default(False) }}"
    volumes: "{{ item.value.volumes }}"
  register: check_collectd_containers
  when:
    - action != "config"
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ collectd_services }}"
  notify:
    - Restart collectd container
